version: '3'

volumes:
  pg_data2:
  static:
  media:

services:
  db4:
    image: postgres:13
    restart: always
    volumes:
      - pg_data2:/var/lib/postgresql/data
    env_file:
      - ./.env  
  backend:
    build: ./backend/
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db4
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    build: ./frontend/
    volumes:
      - ../frontend/:/app/result_build/
      
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/media/
    env_file: .env
    depends_on:
      - frontend
      